Signin://yt-formatted-string[text()='Sign in']
Email://input[@type='email']
Next1://*[@class='RveJvd snByac']
Password://input[@type='password']
Next2://*[@class='RveJvd snByac']
Trending://span[text()='Trending']
Subscription://span[text()='Subscriptions']
Video://*[@class='style-scope ytd-thumbnail']
Like://*[@class='style-scope ytd-toggle-button-renderer']
Subscribechannel://yt-formatted-string[contains(text),'Subscribe']']
